zosc: Core OSC Components
Core OSC Components
Functions
ZoscBundle::ZoscTimeTag::ZoscTimeTag ()
Construct a new ZoscTimeTag object.
ZoscBundle::ZoscTimeTag::ZoscTimeTag (uint64_t value)
Construct a new ZoscTimeTag object.
uint64_t ZoscBundle::ZoscTimeTag::getValue () const
static ZoscTimeTag ZoscBundle::ZoscTimeTag::now ()
Get the current time as a ZoscTimeTag (NTP/nano-second precision)
ZoscBundle::ZoscBundle ()
Construct a new ZoscBundle object.
ZoscBundle::ZoscBundle (const ZoscTimeTag &timeTag)
Construct a new ZoscBundle object.
const ZoscTimeTag & ZoscBundle::getTimeTag () const
Get the time tag of the OSC bundle.
const std::vector< std::variant< ZoscMessage, ZoscBundle > > & ZoscBundle::getElements () const
Get the elements of the OSC bundle.
void ZoscBundle::setTimeTag (const ZoscTimeTag &timeTag)
Set the time tag of the OSC bundle.
void ZoscBundle::addMessage (const ZoscMessage &message)
Add a message to the OSC bundle.
void ZoscBundle::addBundle (const ZoscBundle &bundle)
Add a bundle to the OSC bundle.
std::string ZoscBundle::serialize () const
Serialize the OSC bundle.
static ZoscBundle ZoscBundle::deserialize (const std::string &data)
Deserialize the OSC bundle.
Detailed Description
Function Documentation
addBundle()
void ZoscBundle::addBundle (const ZoscBundle & bundle)
Add a bundle to the OSC bundle.
Parameters
bundle The bundle to add
Definition at line 97 of file ZoscBundle.cpp.
{
    _elements.emplace_back(bundle);
}
Referenced by ZoscBundle::deserialize().
addMessage()
void ZoscBundle::addMessage (const ZoscMessage & message)
Add a message to the OSC bundle.
Parameters
message The message to add
Definition at line 91 of file ZoscBundle.cpp.
{
    _elements.emplace_back(message);
}
Referenced by ZoscBundle::deserialize().
deserialize()
ZoscBundle ZoscBundle::deserialize (const std::string & data) static
Deserialize the OSC bundle.
Parameters
data The data to deserialize
Returns
The deserialized OSC bundle
Exceptions
std::runtime_error if the data is not a valid OSC bundle
Returns
The deserialized OSC bundle
Definition at line 146 of file ZoscBundle.cpp.
{
    if ((data.size() < 16) || (data.substr(0, 7) != "#bundle"))
        throw std::runtime_error("Malformed OSC bundle: Missing #bundle "
                                 "identifier.");
    ZoscBundle bundle;
    size_t pos = 8; // Skip "#bundle" and align to 8 bytes
    // Extract TimeTag
    uint32_t upperBits, lowerBits;
    memcpy(&upperBits, data.data() + pos, sizeof(upperBits));
    memcpy(&lowerBits, data.data() + pos + sizeof(upperBits), sizeof(lowerBits));
    uint64_t timeTag =
        (static_cast<uint64_t>(ntohl(upperBits)) << 32) | ntohl(lowerBits);
    bundle.setTimeTag(ZoscTimeTag(timeTag));
    pos += 8;
    // Extract elements
    while (pos < data.size()) {
        if ((pos + sizeof(uint32_t)) > data.size())
            throw std::runtime_error("Malformed OSC bundle: Missing element "
                                     "size.");
        // Measure element size
        uint32_t size;
        memcpy(&size, (data.data() + pos), sizeof(size));
        size = ntohl(size);
        pos += sizeof(size);
        if ((pos + size) > data.size())
            throw std::runtime_error("Malformed OSC bundle: Element size "
                                     "exceeds available data.");
        // Deserialize element
        std::string elementData = data.substr(pos, size);
        pos += size;
        // Align to 4 bytes
        pos = (pos + 3) & ~3;
        // Determine element type
        if (elementData.substr(0, 7) == "#bundle") {
            bundle.addBundle(ZoscBundle::deserialize(elementData));
        } else {
            bundle.addMessage(ZoscMessage::deserialize(elementData));
        }
    }
    return (bundle);
}
References ZoscBundle::addBundle(), ZoscBundle::addMessage(), ZoscBundle::deserialize(), ZoscMessage::deserialize(), and ZoscBundle::setTimeTag().
Referenced by ZoscBundle::deserialize().
getElements()
const std::vector< std::variant< ZoscMessage, ZoscBundle > > & ZoscBundle::getElements () const
Get the elements of the OSC bundle.
Returns
The elements of the OSC bundle
Definition at line 75 of file ZoscBundle.cpp.
{
    return (_elements);
}
getTimeTag()
const ZoscBundle::ZoscTimeTag & ZoscBundle::getTimeTag () const
Get the time tag of the OSC bundle.
Definition at line 68 of file ZoscBundle.cpp.
{
    return (_timeTag);
}
getValue()
uint64_t ZoscBundle::ZoscTimeTag::getValue () const
Definition at line 25 of file ZoscBundle.cpp.
{
    return (_value);
}
Referenced by ZoscBundle::serialize().
now()
ZoscBundle::ZoscTimeTag ZoscBundle::ZoscTimeTag::now () static
Get the current time as a ZoscTimeTag (NTP/nano-second precision)
Definition at line 30 of file ZoscBundle.cpp.
{
    auto now = std::chrono::system_clock::now(); // Get current time
    // Get number of seconds since last UNIX epoch
    auto secs =
        std::chrono::duration_cast<std::chrono::seconds>(now.time_since_epoch())
            .count();
    // Get microseconds since last second
    auto usecs = std::chrono::duration_cast<std::chrono::nanoseconds>(
                     now.time_since_epoch())
                     .count() %
        1'000'000'000;
    // Convert to NTP
    uint64_t ntpSecs = (static_cast<uint64_t>(secs) + NTP_DIFF);
    // Get NTP fraction
    uint64_t ntpFrac =
        (static_cast<uint64_t>(usecs * (1LL << 32)) / 1'000'000'000);
    return (ZoscTimeTag(ntpSecs << 32 | ntpFrac));
}
References NTP_DIFF.
serialize()
std::string ZoscBundle::serialize () const
Serialize the OSC bundle.
Returns
The serialized OSC bundle
Definition at line 107 of file ZoscBundle.cpp.
{
    std::ostringstream oss;
    // Add the OSC bundle identifier
    oss << "#bundle";
    size_t padding = ((4 - (7 % 4)) % 4);
    oss.write("\0\0\0", padding);
    // Serialize the TimeTag
    uint64_t networkTimeTag =
        htonl(static_cast<uint32_t>(_timeTag.getValue() >> 32));
    uint32_t lowerBits =
        htonl(static_cast<uint32_t>(_timeTag.getValue() & 0xFFFFFFFF));
    oss.write(reinterpret_cast<const char *>(&networkTimeTag),
              sizeof(networkTimeTag));
    oss.write(reinterpret_cast<const char *>(&lowerBits), sizeof(lowerBits));
    // Serialize elements
    for (const auto &element : _elements) {
        std::string serializedElement;
        if (std::holds_alternative<ZoscMessage>(element))
            serializedElement = std::get<ZoscMessage>(element).serialize();
        else if (std::holds_alternative<ZoscBundle>(element))
            serializedElement = std::get<ZoscBundle>(element).serialize();
        // Write size of the element (aligned to 4 bytes)
        uint32_t size = htonl(static_cast<uint32_t>(serializedElement.size()));
        oss.write(reinterpret_cast<const char *>(&size), sizeof(size));
        oss.write(serializedElement.data(), serializedElement.size());
    }
    return (oss.str());
}
References ZoscBundle::ZoscTimeTag::getValue().
Referenced by OscSender::sendBundle().
setTimeTag()
void ZoscBundle::setTimeTag (const ZoscTimeTag & timeTag)
Set the time tag of the OSC bundle.
Parameters
timeTag The time tag of the OSC bundle
Definition at line 85 of file ZoscBundle.cpp.
{
    this->_timeTag = timeTag;
}
Referenced by ZoscBundle::deserialize().
ZoscBundle() [1/2]
ZoscBundle::ZoscBundle (void)
Construct a new ZoscBundle object.
Definition at line 55 of file ZoscBundle.cpp.
                           : _timeTag(ZoscTimeTag::now()) {
}
ZoscBundle() [2/2]
ZoscBundle::ZoscBundle (const ZoscTimeTag & timeTag) explicit
Construct a new ZoscBundle object.
Parameters
timeTag The time tag of the OSC bundle
Definition at line 60 of file ZoscBundle.cpp.
                                                 : _timeTag(timeTag) {
}
ZoscTimeTag() [1/2]
ZoscBundle::ZoscTimeTag::ZoscTimeTag ()
Construct a new ZoscTimeTag object.
Definition at line 13 of file ZoscBundle.cpp.
                                   : _value(0) {
}
ZoscTimeTag() [2/2]
ZoscBundle::ZoscTimeTag::ZoscTimeTag (uint64_t value) explicit
Construct a new ZoscTimeTag object.
Parameters
value The value of the ZoscTimeTag
Definition at line 18 of file ZoscBundle.cpp.
                                                 : _value(value) {
}