zosc: Network OSC Components
Network OSC Components
Functions
ZoscReceiver::ZoscReceiver (uint16_t port)
Constructor to initialize the UDP receiver.
ZoscReceiver::~ZoscReceiver ()
Destructor ensures the receiver stops cleanly.
void ZoscReceiver::start ()
Start the receiver.
void ZoscReceiver::stop ()
Stop the receiver.
void ZoscReceiver::setMessageCallback (const std::function< void(const ZoscMessage &)> &callback)
Set callback for received messages.
void ZoscReceiver::setBundleCallback (const std::function< void(const ZoscBundle &)> &callback)
Set callback for received bundles.
OscSender::OscSender (const std::string &host, uint16_t port)
Constructor to initialize the host, port, and socket.
void OscSender::sendMessage (const ZoscMessage &message)
void OscSender::sendBundle (const ZoscBundle &bundle)
void OscSender::sendRaw (const std::vector< uint8_t > &data)
Detailed Description
Function Documentation
OscSender()
OscSender::OscSender (const std::string & host, uint16_t port)
Constructor to initialize the host, port, and socket.
Parameters
host The host address to send OSC messages to
port The port to send OSC messages to
Definition at line 15 of file ZoscSender.cpp.
    : _host(host), _port(port), _socket(_ioContext) {
    // Set up the endpoint to send data to the specified host and port
    _endpoint =
        asio::ip::udp::endpoint(asio::ip::address::from_string(host), port);
    // Open the UDP socket
    try {
        _socket.open(asio::ip::udp::v4());
        std::cout << "Socket opened successfully for host: " << _host
                  << " on port: " << _port << std::endl;
    } catch (const std::exception &e) {
        std::cerr << "Error opening socket: " << e.what() << std::endl;
        throw;
    }
}
sendBundle()
void OscSender::sendBundle (const ZoscBundle & bundle)
Definition at line 53 of file ZoscSender.cpp.
{
    // Serialize the OSC bundle to a string
    std::string serialBundle = bundle.serialize();
    // Convert the string to a byte array for transmission
    std::vector<uint8_t> data(serialBundle.begin(), serialBundle.end());
    // Send the data using the socket
    std::cout << "Sending to endpoint: " << _endpoint.address().to_string()
              << ":" << _endpoint.port() << std::endl;
    sendRaw(data);
}
References OscSender::sendRaw(), and ZoscBundle::serialize().
sendMessage()
void OscSender::sendMessage (const ZoscMessage & message)
Definition at line 38 of file ZoscSender.cpp.
{
    // Serialize the OSC message to a string
    std::string serialMsg = message.serialize();
    std::cout << "Serialized message: " << serialMsg << std::endl;
    // Convert the string to a byte array for transmission
    std::vector<uint8_t> data(serialMsg.begin(), serialMsg.end());
    // Send the data using the socket
    std::cout << "Sending to endpoint: " << _endpoint.address().to_string()
              << ":" << _endpoint.port() << std::endl;
    sendRaw(data);
}
References OscSender::sendRaw(), and ZoscMessage::serialize().
sendRaw()
void OscSender::sendRaw (const std::vector< uint8_t > & data)
Definition at line 67 of file ZoscSender.cpp.
{
    try {
        // Send data to the endpoint (host and port)
        std::size_t bytesSent = _socket.send_to(asio::buffer(data), _endpoint);
        std::cout << "Sent " << bytesSent << " bytes to "
                  << _endpoint.address().to_string() << ":" << _endpoint.port()
                  << std::endl;
    } catch (const std::exception &e) {
        std::cerr << "Error sending data: " << e.what() << std::endl;
    }
}
Referenced by OscSender::sendBundle(), and OscSender::sendMessage().
setBundleCallback()
void ZoscReceiver::setBundleCallback (const std::function< void(const ZoscBundle &)> & callback)
Set callback for received bundles.
Parameters
callback The function to call when a bundle is received
Definition at line 70 of file ZoscReceiver.cpp.
{
    _bundleCallback = callback;
}
setMessageCallback()
void ZoscReceiver::setMessageCallback (const std::function< void(const ZoscMessage &)> & callback)
Set callback for received messages.
Parameters
callback The function to call when a message is received
Definition at line 63 of file ZoscReceiver.cpp.
{
    _messageCallback = callback;
}
start()
void ZoscReceiver::start ()
Start the receiver.
Definition at line 34 of file ZoscReceiver.cpp.
{
    if (_running)
        return;
    _running = true;
    // Start receiving data
    receive();
    // Run the I/O context in a separate thread
    _ioThread = std::thread([this]() { _ioContext.run(); });
    std::cout << "Receiver started on port " << _port << std::endl;
}
stop()
void ZoscReceiver::stop ()
Stop the receiver.
Definition at line 48 of file ZoscReceiver.cpp.
{
    if (!_running)
        return;
    _running = false;
    // Stop the I/O context and join the thread
    _ioContext.stop();
    if (_ioThread.joinable())
        _ioThread.join();
    std::cout << "Receiver stopped" << std::endl;
}
Referenced by ZoscReceiver::~ZoscReceiver().
ZoscReceiver()
ZoscReceiver::ZoscReceiver (uint16_t port)
Constructor to initialize the UDP receiver.
Parameters
port The port to listen for OSC messages on
Definition at line 13 of file ZoscReceiver.cpp.
    : _port(port),
      _socket(_ioContext, asio::ip::udp::endpoint(asio::ip::udp::v4(), port)),
      _running(false), _receiveBuffer(1024) {
    std::cout << "Receiver initialized on port " << _port << std::endl;
}
~ZoscReceiver()
ZoscReceiver::~ZoscReceiver ()
Destructor ensures the receiver stops cleanly.
Definition at line 25 of file ZoscReceiver.cpp.
{
    stop();
}
References ZoscReceiver::stop().